name: Hardware

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.9
      
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --user
        
    - name: Setup System
      run: |
        sudo apt-get install libsqlite3-dev
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install build-essential
        sudo apt-get install gcc-multilib g++-multilib lib32z1 lib32stdc++6 lib32gcc1 expat:i386 fontconfig:i386 \
        libfreetype6:i386 libexpat1:i386 libc6:i386 libcanberra0:i386 libpng12-0:i386 libice6:i386 \
        libsm6:i386 libncurses5:i386 zlib1g:i386 libx11-6:i386 libxau6:i386 libxdmcp6:i386 libxext6:i386 libxft2:i386 \
        libxrender1:i386 libxt6:i386 libxtst6:i386 curl
        
    - name: Install modelsim
      run: |
        # download and install modelsim
        curl http://download.altera.com/akdlm/software/acdsinst/17.1std/590/ib_installers/ModelSimSetup-17.1.0.590-linux.run -o modelsim.run
        chmod +x modelsim.run
        ./modelsim.run --mode unattended --accept_eula 1 --installdir $HOME
        # corrigi bug modelsim com kernel 4
        sed -i '209 a\        4.[0-9]*)             vco="linux" ;;' $HOME/modelsim_ase/vco
        # # define o modelsim como simulador para o VUNIT
        export VUNIT_SIMULATOR=modelsim
        export VUNIT_MODELSIM_PATH=$HOME/modelsim_ase/bin/

    - name: install z01-tools
      run: |
        bash updateZ01tools.sh
  
    - uses: actions/checkout@v1
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1

  
    - name: run tests
      run: |
        python3 Projetos/C-LogicaCombinacional/testeLogicaCombinacional.py
      env:
         VUNIT_SIMULATOR: modelsim
         VUNIT_MODELSIM_PATH: /home/runner/modelsim_ase/bin/
